algoritmo "idade candidato"
// Autor :Sarah e Samilly
// Data : 14/04/2026
// Seção de Declarações 
var
    idade:inteiro
      javascript, Python: caractere
inicio
// Seção de Comandos 
   Escreva("digite a sua idade:")
   Leia(idade)

   Escreva ("digite sabe javaScript? (s/n):")
   Leia(javaScript)

   Escreva("digite sabe Python? (s/n):")
   Leia(python)

    se (idade >= 18) e (javaScript = "s") e (python = "s") entao
        Escreval("curriculo aceito")
   senao
      Escreval("curriculo nao aceito")

       Fimse

fimalgoritmo

