algoritmo "Estoque"
// F9 executa o meu código

// Autor : Sarah Mendonça
// Data : 14/04/2026

var
esgotado, s, n : literal

inicio
// Seção de Comandos

escreva("Ainda há estoque do produto? (Responda s/n):")

leia(esgotado)

se esgotado = "n" entao

escreva("Produto esgotado. Por favor, reabasteça o estoque.")

senao

escreva("Produto disponível para venda.")

fimse
fimalgoritmo
