algoritmo "Verificação de Senha"
// F9 executa meu programa

// Autor :  Sarah Mendonça
// Data : 14/04/2026

var
// Declarando as variáveis...
nota, frequencia: real

inicio
// Seção de Comandos

escreva("Informe sua nota:")
leia(nota)

escreva("Informe sua frequência:")

leia(frequencia)

se (nota >= 7) e (frequencia >= 0.75) entao

escreva("Parabéns. Você foi aprovado.")

senao

escreva("Sentimos muito. Você foi reprovado.")

fimse

// Prontinho! Nada como uma programação finalizada com sucesso :)
fimalgoritmo
